# ---------------------------
# Application Name
# ---------------------------
spring.application.name=booking-service

# ---------------------------
# Datasource / PostgreSQL
# ---------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/movie_booking?options=-c%20timezone=Asia/Kolkata
spring.datasource.username=movie_user
spring.datasource.password=movie_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------------------
# JPA / Hibernate
# ---------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ---------------------------
# Flyway Migration
# ---------------------------
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:/db/migration

# gRPC server
grpc.server.port=9090

# gRPC clients
grpc.client.seat-service.address=static://localhost:9090
grpc.client.seat-service.negotiationType=plaintext

grpc.client.pricing-service.address=static://localhost:9090
grpc.client.pricing-service.negotiationType=plaintext


# ---------------------------
# Redis
# ---------------------------
spring.data.redis.host=localhost
spring.data.redis.port=6379
